# Generated by Django 4.2.7 on 2023-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_post', models.CharField(max_length=255)),
                ('title_post', models.CharField(max_length=255)),
                ('text_post', models.CharField(max_length=255)),
                ('likes_post', models.PositiveIntegerField()),
            ],
        ),
    ]
